version: 0.0.1
name: navigation

publish_to: none

description: Navigation module

environment:
  sdk: ">=3.4.0 <3.5.0"
  flutter: ">=3.22.0 <3.23.0"

dependencies:
  flutter:
    sdk: flutter

  home:
    path: ../features/home
  tacks:
    path: ../features/tacks
  groups:
    path: ../features/groups

  rxdart: ^0.27.0
  auto_route: 7.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8

flutter:
