name: tack_test_app
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <3.5.0"
  flutter: ">=3.22.0 <3.23.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  core:
    path: ./core

  navigation:
    path: ./navigation
  home:
    path: ./features/home

  utilities:
    path: ./utilities

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - localization/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/manrope/Manrope-ExtraLight.ttf
          weight: 100
        - asset: fonts/manrope/Manrope-Light.ttf
          weight: 200
        - asset: fonts/manrope/Manrope-Regular.ttf
          weight: 300
        - asset: fonts/manrope/Manrope-Medium.ttf
          weight: 400
        - asset: fonts/manrope/Manrope-SemiBold.ttf
          weight: 500
        - asset: fonts/manrope/Manrope-Bold.ttf
          weight: 600
        - asset: fonts/manrope/Manrope-ExtraBold.ttf
          weight: 700
