name: utilities
description: A new Flutter project.
version: 0.0.1
homepage: none

environment:
  sdk: ">=3.4.0 <3.5.0"
  flutter: ">=3.22.0 <3.23.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: