name: core
description: A new Flutter project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.4.0 <3.5.0"
  flutter: ">=3.22.0 <3.23.0"

dependencies:
  flutter:
    sdk: flutter

  navigation:
    path: ../navigation

  intl: ^0.19.0
  get_it: ^7.2.0
  flutter_bloc: ^7.3.3
  flutter_i18n: ^0.35.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
